---

# - name: Flush memcached
#   shell: memcflush --servers=localhost:11211

- name: Run collectstatic
  django_manage:
    app_path: "{{ project_home }}/src/"
    command: collectstatic
    link: yes
    settings: "{{ settings_module }}"
    virtualenv: "{{ venv }}"
